version: 2.1

jobs:
  run_tests:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          name: Install npm dependencies
          command: npm install --save

  build_docker_image:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: Build Docker image
          command: |
            docker build -t $DOCKER_USERNAME/reactservapp:latest -t $DOCKER_USERNAME/mynextapp:latest .
      - run:
          name: Log in to Docker Hub
          command: |
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
      - run:
          name: Push Docker image to Docker Hub
          command: |
            docker push $DOCKER_USERNAME/reactservapp:latest
            docker push $DOCKER_USERNAME/mynextapp:latest

workflows:
  version: 2
  build_and_test:
    jobs:
      - run_tests
      - build_docker_image:
          requires:
            - run_tests
